name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: terraform init

      - name: Terraform Apply
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: terraform apply -auto-approve -var="vercel_token=${{ secrets.VERCEL_TOKEN }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add this to your GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add this to your GitHub Secrets

      - name: Build and Push Docker Image
        run: |
          docker build -t tabrezdn1/hacknjit24-fe:latest .  # Replace with your Docker image name
          docker push tabrezdn1/hacknjit24-fe:latest        # Push image to Docker Hub

      - name: Deploy to Vercel
        run: terraform apply -auto-approve
